# 工作流名称
name: Sort IPs with Python

# 触发条件：支持手动触发和推送触发
on:
  push:  # 推送代码时自动触发
    paths:
      - '4.txt'  # 只有当4.txt或6.txt文件被推送时才触发
      - '6.txt'
  workflow_dispatch:  # 手动触发
    inputs:
      manualTrigger:
        description: 'Manual Trigger'  # 手动触发的描述
        required: false
        default: 'true'

# 定义工作流中的任务
jobs:
  sort-ips:
    # 使用最新的Ubuntu环境运行任务
    runs-on: ubuntu-latest

    steps:
      # 检出代码，确保4.txt和6.txt文件可用
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安装Python依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # 运行Python脚本处理IP文件
      - name: Run Python script to sort IPs
        run: |
          python sort_ips.py

      # 提交并推送处理后的文件（ipv4.txt和ipv6.txt）
      - name: Commit and push sorted files
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # 使用个人访问令牌
        run: |
          git config --global user.name "github-actions[bot]"  # 配置Git用户信息
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ipv4.txt ipv6.txt  # 添加生成的文件
          git commit -m "Update sorted IP files" || echo "No changes to commit"  # 提交更改
          git push origin HEAD  # 推送到仓库
